services:
    langgraph:
      build: .
      ports:
        - 8888:8888
        - 2024:2024
      volumes:
        - ./:/home/jupyter/work
      environment:
          - PYTHONUNBUFFERED=1
          - OPENAI_API_KEY=${OPENAI_API_KEY}
          - TAVILY_API_KEY=${TAVILY_API_KEY}
          - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
          - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      restart: unless-stopped
